package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/ericismyeldestson/chinese-poetry-api/internal/api/searchquery"
	"github.com/ericismyeldestson/chinese-poetry-api/internal/database"
	"github.com/ericismyeldestson/chinese-poetry-api/internal/graph/generated"
	"github.com/ericismyeldestson/chinese-poetry-api/internal/graph/model"
)

// Poems is the resolver for the poems field.
func (r *authorResolver) Poems(ctx context.Context, obj *database.Author, page *int, pageSize *int) (*database.PoemConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}
	lang, err := authorLanguage(ctx, obj)
	if err != nil {
		return nil, err
	}

	poems, totalCount, err := r.Repo.WithLang(lang).ListAuthorPoems(obj.ID, pag.PageSize, pag.Offset)
	if err != nil {
		return nil, err
	}

	connection := buildPoemConnection(poems, pag, totalCount)
	registerPoemConnectionLanguage(ctx, connection, lang)
	if err := r.prefetchPoemRelationCounts(ctx, lang, poems); err != nil {
		return nil, err
	}
	return connection, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *authorResolver) PoemCount(ctx context.Context, obj *database.Author) (int, error) {
	lang, err := authorLanguage(ctx, obj)
	if err != nil {
		return 0, err
	}
	if count, ok := authorCount(ctx, lang, obj.ID); ok {
		return count, nil
	}
	return r.Repo.WithLang(lang).CountPoemsByAuthor(obj.ID)
}

// Node is the resolver for the node field.
func (r *authorEdgeResolver) Node(ctx context.Context, obj *database.AuthorEdge) (*database.Author, error) {
	return &obj.Node.Author, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *dynastyResolver) PoemCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	lang, err := languageForPath(ctx)
	if err != nil {
		return 0, err
	}
	if counts, ok := dynastyStats(ctx, lang, obj.ID); ok {
		return counts.poems, nil
	}
	return r.Repo.WithLang(lang).CountPoemsByDynasty(obj.ID)
}

// AuthorCount is the resolver for the authorCount field.
func (r *dynastyResolver) AuthorCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	lang, err := languageForPath(ctx)
	if err != nil {
		return 0, err
	}
	if counts, ok := dynastyStats(ctx, lang, obj.ID); ok {
		return counts.authors, nil
	}
	return r.Repo.WithLang(lang).CountAuthorsByDynasty(obj.ID)
}

// Content is the resolver for the content field.
func (r *poemResolver) Content(ctx context.Context, obj *database.Poem) ([]string, error) {
	var content []string
	if err := json.Unmarshal(obj.Content, &content); err != nil {
		return nil, err
	}
	return content, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *poetryTypeResolver) PoemCount(ctx context.Context, obj *database.PoetryType) (int, error) {
	lang, err := languageForPath(ctx)
	if err != nil {
		return 0, err
	}
	if count, ok := typeCount(ctx, lang, obj.ID); ok {
		return count, nil
	}
	return r.Repo.WithLang(lang).CountPoemsByType(obj.ID)
}

// Poem is the resolver for the poem field.
func (r *queryResolver) Poem(ctx context.Context, id string, lang *database.Lang) (*database.Poem, error) {
	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)

	poem, err := repo.GetPoemByID(id)
	if err != nil {
		return nil, err
	}
	registerPoemLanguage(ctx, poem, langVal)
	return poem, nil
}

// Poems is the resolver for the poems field.
func (r *queryResolver) Poems(ctx context.Context, lang *database.Lang, page *int, pageSize *int, dynastyID *string, authorID *string, typeID *string) (*database.PoemConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	// 解析各项过滤 ID
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}
	authorIDInt, err := parseOptionalID(authorID)
	if err != nil {
		return nil, err
	}
	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}

	// GraphQL schema 只暴露单个 typeID；仓储层接收切片，
	// 是因为 REST 接口允许重复传入 type_id 参数。
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	poems, totalCount, err := repo.ListPoemsWithFilter(pag.PageSize, pag.Offset, dynastyIDInt, authorIDInt, typeIDs)
	if err != nil {
		return nil, err
	}

	connection := buildPoemConnection(poems, pag, totalCount)
	registerPoemConnectionLanguage(ctx, connection, langVal)
	if err := r.prefetchPoemRelationCounts(ctx, langVal, poems); err != nil {
		return nil, err
	}
	return connection, nil
}

// SearchPoems is the resolver for the searchPoems field.
func (r *queryResolver) SearchPoems(ctx context.Context, query string, lang *database.Lang, searchType *model.SearchType, page *int, pageSize *int) (*database.PoemConnection, error) {
	query, err := searchquery.Normalize(query)
	if err != nil {
		return nil, err
	}

	// 统一走公共的解析函数，而非直接读取参数——
	// 后者正是本 resolver 曾经绕过 pageSize 上限的原因。
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	// 把 GraphQL 的搜索类型映射为仓储层的取值
	st := "all"
	if searchType != nil {
		switch *searchType {
		case model.SearchTypeTitle:
			st = "title"
		case model.SearchTypeContent:
			st = "content"
		case model.SearchTypeAuthor:
			st = "author"
		}
	}
	if st != "author" {
		if err := searchquery.ValidateIndexedLength(query); err != nil {
			return nil, err
		}
	} else if err := searchquery.ValidateLiteralSubstring(query); err != nil {
		return nil, err
	}

	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	poems, total, err := repo.SearchPoems(ctx, query, st, pag.Page, pag.PageSize)
	if err != nil {
		return nil, err
	}

	// 用公共函数构造 connection，不再手写。手写版本的游标在每页内都从 0 开始编号，
	// 导致第 2 页首条边的游标与第 1 页的相同；而且没有填 startCursor 与 endCursor，
	// 与其他所有 connection 的行为不一致。
	connection := buildPoemConnection(poems, pag, int(total))
	registerPoemConnectionLanguage(ctx, connection, langVal)
	if err := r.prefetchPoemRelationCounts(ctx, langVal, poems); err != nil {
		return nil, err
	}
	return connection, nil
}

// RandomPoem is the resolver for the randomPoem field.
func (r *queryResolver) RandomPoem(ctx context.Context, lang *database.Lang, dynastyID *string, typeID *string) (*database.Poem, error) {
	// 解析过滤 ID。格式错误的 ID 一律报错，而不是丢弃该过滤条件：
	// 被丢弃的过滤条件会把查询范围扩大到全量语料并返回一首无关的诗，
	// 这与一次正常请求毫无区别。
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	// 与 REST 一致，带语言上下文调用仓储层的 GetRandomPoem
	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	poem, err := repo.GetRandomPoem(dynastyIDInt, nil, typeIDs)
	if err != nil {
		return nil, err
	}
	registerPoemLanguage(ctx, poem, langVal)
	return poem, nil
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string, lang *database.Lang) (*database.Author, error) {
	authorID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}

	// 走 Repository 的方法，由它处理动态表名
	langVal := parseLang(lang)
	author, err := r.Repo.WithLang(langVal).GetAuthorByID(authorID)
	if err != nil {
		return nil, err
	}
	registerAuthorLanguage(ctx, author, langVal)
	return author, nil
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context, lang *database.Lang, page *int, pageSize *int, dynastyID *string) (*database.AuthorConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	authors, totalCount, err := repo.ListAuthorsWithFilter(pag.PageSize, pag.Offset, dynastyIDInt)
	if err != nil {
		return nil, err
	}

	connection := buildAuthorConnection(authors, pag, totalCount)
	registerAuthorConnectionLanguage(ctx, connection, langVal)
	for _, author := range authors {
		cacheAuthorCount(ctx, langVal, author.ID, author.PoemCount)
	}
	if err := r.prefetchAuthorDynastyStats(ctx, langVal, authors); err != nil {
		return nil, err
	}
	return connection, nil
}

// Dynasties is the resolver for the dynasties field.
func (r *queryResolver) Dynasties(ctx context.Context, lang *database.Lang) ([]*database.Dynasty, error) {
	langVal := parseLang(lang)
	dynastyTable := database.DynastiesTable(langVal)
	poemTable := database.PoemsTable(langVal)
	var rows []struct {
		database.Dynasty
		PoemCount   int `gorm:"column:poem_count"`
		AuthorCount int `gorm:"column:author_count"`
	}
	err := r.DB.Table(dynastyTable).
		Select(dynastyTable + ".*, COUNT(" + poemTable + ".id) AS poem_count, COUNT(DISTINCT " + poemTable + ".author_id) AS author_count").
		Joins("LEFT JOIN " + poemTable + " ON " + dynastyTable + ".id = " + poemTable + ".dynasty_id").
		Group(dynastyTable + ".id").Order(dynastyTable + ".id").Scan(&rows).Error
	if err != nil {
		return nil, err
	}
	dynasties := make([]*database.Dynasty, len(rows))
	registerEntityLanguage(ctx, langVal)
	for i := range rows {
		dynasties[i] = &rows[i].Dynasty
		cacheDynastyStats(ctx, langVal, rows[i].ID, rows[i].PoemCount, rows[i].AuthorCount)
	}
	return dynasties, nil
}

// PoemTypes is the resolver for the poemTypes field.
func (r *queryResolver) PoemTypes(ctx context.Context, lang *database.Lang) ([]*database.PoetryType, error) {
	langVal := parseLang(lang)
	typeTable := database.PoetryTypesTable(langVal)
	poemTable := database.PoemsTable(langVal)
	var rows []struct {
		database.PoetryType
		PoemCount int `gorm:"column:poem_count"`
	}
	err := r.DB.Table(typeTable).
		Select(typeTable + ".*, COUNT(" + poemTable + ".id) AS poem_count").
		Joins("LEFT JOIN " + poemTable + " ON " + typeTable + ".id = " + poemTable + ".type_id").
		Group(typeTable + ".id").Order(typeTable + ".id").Scan(&rows).Error
	if err != nil {
		return nil, err
	}
	types := make([]*database.PoetryType, len(rows))
	registerEntityLanguage(ctx, langVal)
	for i := range rows {
		types[i] = &rows[i].PoetryType
		cacheTypeCount(ctx, langVal, rows[i].ID, rows[i].PoemCount)
	}
	return types, nil
}

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context, lang *database.Lang) (*database.Statistics, error) {
	langVal := parseLang(lang)
	stats, err := r.Repo.WithLang(langVal).GetStatistics()
	if err != nil {
		return nil, err
	}
	registerEntityLanguage(ctx, langVal)

	dynastyPoemCounts := make(map[int64]int, len(stats.PoemsByDynasty))
	for _, stat := range stats.PoemsByDynasty {
		dynastyPoemCounts[stat.ID] = stat.PoemCount
		cacheDynastyStats(ctx, langVal, stat.ID, stat.PoemCount, 0)
	}
	if len(dynastyPoemCounts) > 0 {
		var rows []struct {
			ID          int64 `gorm:"column:id"`
			AuthorCount int   `gorm:"column:author_count"`
		}
		if err := r.DB.Table(database.PoemsTable(langVal)).
			Select("dynasty_id AS id, COUNT(DISTINCT author_id) AS author_count").
			Where("dynasty_id IN ?", mapKeysForCounts(dynastyPoemCounts)).
			Group("dynasty_id").Scan(&rows).Error; err != nil {
			return nil, err
		}
		for _, row := range rows {
			cacheDynastyStats(ctx, langVal, row.ID, dynastyPoemCounts[row.ID], row.AuthorCount)
		}
	}
	for _, stat := range stats.PoemsByType {
		cacheTypeCount(ctx, langVal, stat.ID, stat.PoemCount)
	}
	return stats, nil
}

// PoemsByDynasty is the resolver for the poemsByDynasty field.
func (r *statisticsResolver) PoemsByDynasty(ctx context.Context, obj *database.Statistics) ([]*model.DynastyStats, error) {
	stats := make([]*model.DynastyStats, len(obj.PoemsByDynasty))
	for i, ds := range obj.PoemsByDynasty {
		stats[i] = &model.DynastyStats{
			Dynasty: &ds.Dynasty,
			Count:   ds.PoemCount,
		}
	}
	return stats, nil
}

// PoemsByType is the resolver for the poemsByType field.
func (r *statisticsResolver) PoemsByType(ctx context.Context, obj *database.Statistics) ([]*model.TypeStats, error) {
	stats := make([]*model.TypeStats, len(obj.PoemsByType))
	for i, ts := range obj.PoemsByType {
		stats[i] = &model.TypeStats{
			Type:  &ts.PoetryType,
			Count: ts.PoemCount,
		}
	}
	return stats, nil
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

// AuthorEdge returns generated.AuthorEdgeResolver implementation.
func (r *Resolver) AuthorEdge() generated.AuthorEdgeResolver { return &authorEdgeResolver{r} }

// Dynasty returns generated.DynastyResolver implementation.
func (r *Resolver) Dynasty() generated.DynastyResolver { return &dynastyResolver{r} }

// Poem returns generated.PoemResolver implementation.
func (r *Resolver) Poem() generated.PoemResolver { return &poemResolver{r} }

// PoetryType returns generated.PoetryTypeResolver implementation.
func (r *Resolver) PoetryType() generated.PoetryTypeResolver { return &poetryTypeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Statistics returns generated.StatisticsResolver implementation.
func (r *Resolver) Statistics() generated.StatisticsResolver { return &statisticsResolver{r} }

type (
	authorResolver     struct{ *Resolver }
	authorEdgeResolver struct{ *Resolver }
	dynastyResolver    struct{ *Resolver }
	poemResolver       struct{ *Resolver }
	poetryTypeResolver struct{ *Resolver }
	queryResolver      struct{ *Resolver }
	statisticsResolver struct{ *Resolver }
)
